In [1]:
import matplotlib.pyplot as plt
import numpy as np
import scipy.io as sio

In [12]:
data = sio.loadmat(r"C:\Users\luisa\Downloads\S0546.mat")
sio.whosmat(r"C:\Users\luisa\Downloads\S0546.mat")
datos= np.array(data["val"])
print(datos)

[[  806   809   831 ...  -396  -392  -384]
 [ -295  -300  -298 ...   678   678   679]
 [-1100 -1109 -1129 ...  1074  1070  1063]
 ...
 [  355   351   349 ... -1296 -1294 -1289]
 [  483   480   481 ... -1579 -1574 -1566]
 [  871   873   877 ... -1629 -1624 -1618]]


In [9]:
class Señal():
    def __init__(self):
        self.__datos = datos
        self.__canales = datos.shape[0]
        self.__puntos = datos.shape[1]
        self.__epocas = datos.shape[2]
        self.__tamaño = datos.ndim

    def AsignardatosM(self):
        info = input("Ingrese la dirección del archivo: ")
        arch = sio.loadmat(info)
        print(arch.values)
        llave = input("Ingrese la llave del archivo a manipular")
        datos = np.array(arch[llave])
        self.__datos = datos

    #def AsignardatosC():

    def Obtenercanales(self):
        return self.__canales
    
    def Obtenerpuntos(self):
        return self.__puntos
    
    def Obtenerepocas(self):
        return self.__epocas
    
    
        


<built-in method keys of dict object at 0x00000245EC51D780>


In [ ]:
class Graficadora(Señal):
    def __init__(self):